#!/bin/sh
#
# Create FHS directories below a target directory.
#
# Copyright (C) 2011  Codethink Limited
# 
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; version 2 of the License.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

set -e

if [ "$#" != 1 ]
then
    echo "Error: must give target root directory as argument." 1>&2
    exit 1
fi

DESTDIR=$1
mknod -m 600 "$DESTDIR/dev/console" c 5 1
mknod -m 666 "$DESTDIR/dev/null" c 1 3
