#!/bin/sh
#
# Create FHS directories below a target directory.
#
# Copyright (C) 2011  Codethink Limited
# 
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; version 2 of the License.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

set -e

if [ "$#" != 1 ]
then
    echo "Error: must give target root directory as argument." 1>&2
    exit 1
fi

DESTDIR=$1
while read path mode type major minor; do
    mknod -m "$mode" "$DESTDIR/$path" "$type" "$major" "$minor"
done <<EOF
/dev/console 600 c 5 1
/dev/full    666 c 1 7
/dev/null    666 c 1 3
/dev/urandom 666 c 1 9
/dev/zero    666 c 1 5
EOF
