#!/bin/sh
#
# Create FHS directories below a target directory.
#
# Copyright (C) 2011, 2016  Codethink Limited
# 
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; version 2 of the License.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

set -ex

if [ "$#" -lt 1 ]
then
    echo "USAGE: $0 <target-dir> [<dirs-file>] [<links-file>]" 1>&2
    echo "Error: must give target root directory as argument." 1>&2
    exit 1
fi

target="$1"

defaultowner=root
defaultgroup=root
defaultperms=0755

if [ ! "$2" ]
then
    directories=directories
fi

if [ ! "$3"]
then
    links=links
fi

while read dirname perms owner group
do
    if [ ! "$perms" ]
    then
        perms=$defaultperms
    fi
    if [ ! "$owner" ]
    then
        owner=$defaultowner
    fi
    if [ ! "$group" ]
    then
        group=$defaultgroup
    fi

    if [ "$dirname" ]
    then
        install -d -o "$owner" -g "$group" -m "$perms" "$target/$dirname"
    fi
    owner=""
    group=""
    perms=""
done < $directories

while read link name; do
    ln -s "$link" "$target/$name"
done < $links
