#!/bin/sh
rm /etc/mtab
touch /etc/mtab
mount -t proc proc /proc
mount -t sysfs sysfs /sys
mkdir -p /dev/pts
mount -t devpts devpts /dev/pts

echo /sbin/mdev >/proc/sys/kernel/hotplug
mdev -s

hostname -F /etc/hostname

ifdown eth0
ifup eth0
